import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [searchInput, setSearchInput] = useState("");
  const [filteredWeapon, setFilteredWeapon] = useState("");
  const [filteredColor, setFilteredColor] = useState("");
  const [currentTab, setCurrentTab] = useState<"hero" | "hero-details">("hero-details");
  const [hero, setHero] = useState<Partial<{ name: string; skills: any[]; boon: ""; bane: "", resplendent: boolean; merges: number; level: number; rarity: number; stats: {
    hp: number;
    atk: number;
    spd: number;
    def: number;
    res: number;
  } }>>({
    name: "Chrom: Exalted Prince"
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <nav style={{ width: "100%" }}>
          <ul style={{ display: "flex", listStyleType: "none" }}>
            <li style={{ flex: 1 }}>
              <button style={{ width: "100%" }}>Chrom: Exalted Prince</button>
            </li>
            <li style={{ flex: 1 }}>
              <button style={{ width: "100%" }}>New Hero</button>
            </li>
          </ul>
        </nav>
        <div style={{ display: currentTab !== "hero" ? "none" : "block" }}>
          <form style={{ width: "100%" }}>
            <fieldset>
              <legend>Filters</legend>
              <dl>
                <dt><label id="name" htmlFor="name-input">Hero Name</label></dt>
                <dd><input id="name-input" autoComplete="off" aria-labelledby='name' value={searchInput} onChange={(e) => {
                  setSearchInput(e.target.value);
                }} /></dd>
                <dt><label id="hero-color" htmlFor='color-selector'>
                  Hero Color
                </label></dt>
                <dd><select onChange={(e) => {
                  setFilteredColor(e.target.value);
                }} value={filteredColor} aria-describedby='color-warning' id="color-selector" aria-labelledby='hero-color'>
                  <option></option>
                  <option>Red</option>
                  <option>Blue</option>
                  <option>Green</option>
                  <option>Colorless</option>
                </select></dd>
                <dt><label id="hero-weapon" htmlFor='weapon-selector'>
                  Hero Weapon
                </label></dt>
                <dd><select onChange={(e) => {
                  setFilteredWeapon(e.target.value);
                }} value={filteredWeapon} aria-describedby='hero-weapon' id="weapon-selector">
                  <option></option>
                  <optgroup label="Close Range">
                    <option>Sword</option>
                    <option>Lance</option>
                    <option>Axe</option>
                    <option>Beast</option>
                    <option>Breath</option>
                  </optgroup>
                  <optgroup label="Long Range">
                    <option>Bow</option>
                    <option>Tome</option>
                    <option>Dagger</option>
                  </optgroup>
                </select></dd>
                <dt><label id="hero-movement" htmlFor='movement-selector'>Movement</label></dt>
                <dd><select id="movement-selector" aria-labelledby='hero-movement'>
                  <option></option>
                  <option>Infantry</option>
                  <option>Armored</option>
                  <option>Flier</option>
                  <option>Cavalry</option>
                </select></dd>
              </dl>
              <p id="color-warning">Color selection can be overriden by weapon choice, if only one color of that weapon exists (ex. Swords are always Red).</p>
            </fieldset>
          </form>
          <div aria-relevant="all" aria-live="polite">
            Found 100 results.
          </div>
          <table>
            <thead onClick={(e) => {
              // @ts-ignore
              console.log(e.target)
            }}>
              <tr>
                <th><button>Hero</button></th>
                <th><button>Movement</button></th>
                <th><button>Color</button></th>
                <th><button>Weapon</button></th>
                <th><button>HP</button></th>
                <th><button>Atk</button></th>
                <th><button>Spd</button></th>
                <th><button>Def</button></th>
                <th><button>Res</button></th>
                <th><button>BST</button></th>
              </tr>
            </thead>
            <tbody onClick={console.log}>
              <tr>
                <td><p>Chrom</p><p>Exalted Prince</p></td>
                <td>Infantry</td>
                <td>Red</td>
                <td>Sword</td>
                <td>60</td>
                <td>70</td>
                <td>36</td>
                <td>41</td>
                <td>30</td>
                <td>237</td>
              </tr>
              <tr>
                <td>
                  <p>Chrom</p>
                  <p>Exalted Prince</p>
                </td>
                <td>Armored</td>
                <td>Green</td>
                <td>Axe</td>
                <td>60</td>
                <td>70</td>
                <td>36</td>
                <td>41</td>
                <td>30</td>
                <td>237</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div style={{ display: currentTab !== "hero-details" ? "none" : "block" }}>
          <div style={{ display: "flex" }}>
            <div style={{ flex: 1 }}>
              <div style={{ textAlign: "center" }}>
                <Image src="" loading="lazy" alt="" height={40} width={40} style={{ margin: "auto", backgroundColor: "red" }} />
              </div>
              <p style={{ textAlign: "center" }} aria-label="Hero name">{hero.name}</p>
            </div>
            <div style={{ flex: 1 }}>
              <h4 aria-label="Hero Details">Details</h4>
              <button aria-description="Edit the hero's level, merges, rarity, and if applicable, if they are resplendent">
                <span style={{ display: "block" }}>Rarity: 5 stars.</span>
                <span>Level: 40.</span>
                <span>Merges: 10.</span>
                <span>Resplendent: No.</span>
                <span>Boon / Bane: None.</span>
              </button>
            </div>
            <div style={{ flex: 1 }}>
              <h4 id="moveset-section-title">Moveset</h4>
              <dl>
                <dt><label htmlFor='weapon-slot'>Weapon</label></dt>
                <dd><input id="weapon-slot" autoComplete='off' value="Sealed Falchion" /></dd>
                <dt><label htmlFor='passive-a'>A Passive</label></dt>
                <dd><input id="passive-a" autoComplete='off' value="HP+5" /></dd>
                <dt><label htmlFor='passive-b'>B Passive</label></dt>
                <dd><input id="passive-b" autoComplete='off' value="Vantage 3" /></dd>
                <dt><label htmlFor='passive-c'>C Passive</label></dt>
                <dd><input autoComplete='off' id="passive-c" value="Atk Smoke 3" /></dd>
                <dt><label htmlFor='sacred-seal'>Sacred Seal</label></dt>
                <dd><input id="sacred-seal" autoComplete="off" value="Poison Strike 3" /></dd>
              </dl>
            </div>
            <div style={{ flex: 1 }}>
              <h4>Stats</h4>
              <table aria-label={`Stats for ${hero.name}`} aria-atomic aria-live="polite">
                <tbody>
                  <tr><td></td><td scope="row">HP</td><td>59</td></tr>
                  <tr><td scope='row'>Atk</td><td>70</td><td scope="row">Def</td><td>46</td></tr>
                  <tr><td scope="row">Spd</td><td>37</td><td scope="row">Res</td><td>32</td></tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
